[Interface]
# Bouncing = 2
# NAT-PMP (Port Forwarding) = on
# VPN Accelerator = on
PrivateKey = cMWp5oYAlagkIBVOnuHnaGXKGxYX54M5hoBRAY48g1o=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# CH-FREE#11
PublicKey = L6Vcy4PWQOyzFsjOI0GNCDypvzZfTuuZ14qmR1sT5QE=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 135.136.39.34:51820

PersistentKeepalive = 25