[Interface]
# Bouncing = 1
# NAT-PMP (Port Forwarding) = on
# VPN Accelerator = on
PrivateKey = iDjahrt7TQdumoEvO81Q+F2knf60jGhrpRbc0jidAXw=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# NL-FREE#156
PublicKey = pUY22Gd3zhSoZZO6p0rxg2F96gwNgkpFjYSun4TWf2s=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 185.107.56.22:51820

PersistentKeepalive = 25