[Interface]
# Bouncing = 2
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = YKVJ7lbX8bmiX4kothtr0NMOciP8Hdfk5hk9bmIrzkE=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# SG-FREE#9
PublicKey = dhtz5+jUyF+37NmZc2WIEOTf7/UTJlaT1ojEGkPMPiI=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 149.88.23.107:51820

PersistentKeepalive = 25