[Interface]
# Bouncing = 3
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = qAsEB7zKb3ItV3r4/1VbDyhKauGsgDEJrJVxHspkV0Q=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# US-FREE#69
PublicKey = ljr0KidoBwgj8ZRs4DOCl7GbXMOwGeqJeYUHV9bt20o=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 149.102.226.238:51820

PersistentKeepalive = 25